language: rust

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - PROJECT_NAME=reural_network
    - RUST_BACKTRACE=1
    - RUSTFLAGS='-C link-dead-code'

jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update; fi
  - rustup component add clippy

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libiberty-dev
      - cmake
      - gcc
      - binutils-dev
      - zlib1g-dev

script:
  - cargo doc --verbose --no-deps
  - cargo check --verbose --all
  - cargo clippy --verbose --all
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --verbose --all --release

after_success:
  - bash scripts/kcov.sh
